targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        enabled: false
  web:
    auto_apply_builders: false
    dependencies: [ '$default' ]
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - web/**.dart
        release_options:
          compiler: dart2js
          dart2js_args:
            - --minify
            - --no-source-maps
            - --lax-runtime-type-to-string
            - --trust-primitives
            - --omit-implicit-checks
            - --omit-as-casts
  node:
    auto_apply_builders: false
    dependencies: [ '$default' ]
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - node/**.dart
        options:
          compiler: dart2js
        release_options:
          dart2js_args:
            - --minify
            - --no-source-maps
            - --lax-runtime-type-to-string
            - --trust-primitives
            - --omit-implicit-checks
            - --server-mode
        dev_options:
          dart2js_args:
            - --server-mode
            - -DGLTF_VALIDATOR_DEBUG=true
