targets:
  $default:
    sources:
      - "pubspec.yaml"
      - "bin/gltf_validator.dart"
      - "lib/**"
      - "node/gltf_validator.dart"
      - "web/**"
    builders:
      "|version_builder":
        enabled: True
      "|snapshot_builder":
        generate_for:
          - bin/**.dart
        release_options:
          # Keep this under release_options until https://github.com/dart-lang/build/issues/1127
          snapshot_kind: app-jit
      build_node_compilers|entrypoint:
        generate_for:
          - node/**.dart
        options:
          compiler: dart2js
        release_options:
          dart2js_args:
            - --minify
            - --categories=Server
            - --trust-primitives
            - --trust-type-annotations
        dev_options:
          dart2js_args:
            - -DGLTF_VALIDATOR_DEBUG=true
      build_web_compilers|entrypoint:
        generate_for:
          - web/**.dart
        release_options:
          compiler: dart2js
          dart2js_args:
          - --minify
#          - --no-source-maps
          - --trust-primitives
          - --trust-type-annotations

builders:
  version_builder:
    build_to: source
    # See https://github.com/dart-lang/build/issues/1423
    import: ../../../tool/version_builder.dart
    builder_factories:
      - versionBuilder
    build_extensions:
      "$lib$":
        - gltf.g.dart
  snapshot_builder:
    # See https://github.com/dart-lang/build/issues/1423
    import: ../../../tool/snapshot_builder.dart
    builder_factories:
      - snapshotBuilder
    build_extensions:
      ".dart":
        - .snapshot
