name: gltf
version: 2.0.0-dev.2.4
description: Library for loading and validating glTF 2.0 assets
author: The Khronos Group Inc.
homepage: https://github.com/KhronosGroup/glTF-Validator

dependencies:
  args: '^1.4.3'
  isolate: '^2.0.0'
  meta: '^1.1.5'
  path: '^1.6.0'
  vector_math: '^2.0.7'
  yaml: '^2.1.14'

dev_dependencies:
  build_runner: '^0.9.1'
  build_web_compilers: '^0.4.0'
  build_node_compilers: '^0.1.8'
  grinder: '^0.8.2'
  js: '^0.6.1'
  node_preamble: '^1.4.3'
  test: '^1.2.0'

environment:
  sdk: '>=2.0.0-dev.66.0 <2.0.0'

executables:
  gltf_validator: