name: gltf
version: 2.0.0-dev.2.5
description: Library for loading and validating glTF 2.0 assets
author: The Khronos Group Inc.
homepage: https://github.com/KhronosGroup/glTF-Validator

dependencies:
  args: '^1.5.0'
  isolate: '^2.0.2'
  meta: '^1.1.6'
  path: '^1.6.2'
  vector_math: '^2.0.8'
  yaml: '^2.1.15'

dev_dependencies:
  build_runner: '^0.10.1+1'
  build_web_compilers: '^0.4.2+2'
  build_node_compilers: '^0.1.12'
  grinder: '^0.8.3'
  js: '^0.6.1+1'
  node_preamble: '^1.4.4'
  test: '^1.3.0'

environment:
  sdk: '>=2.0.0 <3.0.0'

executables:
  gltf_validator: