name: gltf
version: 2.0.0-dev.2.2
description: Library for loading and validating glTF 2.0 assets
author: The Khronos Group Inc.
homepage: https://github.com/KhronosGroup/glTF-Validator

dependencies:
  args: '^1.4.3'
  isolate: '^2.0.0'
  meta: '^1.1.5'
  path: '^1.5.1'
  vector_math: '^2.0.7'
  yaml: '^2.1.14'

dev_dependencies:
  archive: '^1.0.0'
  build_runner: '^0.8.9'
  build_web_compilers: '^0.4.0'
  build_node_compilers: '^0.1.3'
  grinder: '^0.8.2'
  js: '^0.6.1'
  node_preamble: '^1.4.2'
  test: '>=0.12.0 <0.13.0'

environment:
  sdk: '>=2.0.0-dev.59.0 <2.0.0'

executables:
  gltf_validator: