name: gltf
version: 2.0.0-dev.1.9
description: Library for loading and validating glTF 2.0 assets
author: The Khronos Group Inc.
homepage: https://github.com/KhronosGroup/glTF-Validator

dependencies:
  args: '^1.4.1'
  isolate: '^1.1.0'
  meta: '^1.1.2'
  path: '^1.5.1'
  vector_math: '^2.0.6'
  yaml: '^2.1.13'

dev_dependencies:
  archive: '^1.0.0'
  grinder: '^0.8.1'
  js: '^0.6.1'
  node_preamble: '^1.4.0'
  test: '>=0.12.0 <0.13.0'

dependency_overrides:
  isolate: '2.0.0'

environment:
  sdk: '>=2.0.0-dev.43.0 <2.0.0'

executables:
  gltf_validator:

transformers:
 - $dart2js:
     commandLineOptions: [--trust-primitives, --trust-type-annotations]

web:
  compiler:
    debug: dartdevc